version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: sudo npm install hexo-cli -g

      - run: git config --global user.email "trungpv1601@gmail.com"
      - run: git config --global user.name "Circle CI"
      - run: sed -i'' "s~https://github.com/trungpv1601/trungpv1601.github.io.git~https://${GH_TOKEN}:x-oauth-basic@github.com/trungpv1601/trungpv1601.github.io.git~" _config.yml
      - run: rm -rf .deploy_git/
      - run: hexo clean
      - run: hexo deploy --generate
